### ISSUE TITLE
Add 5 points doesn't work

### ISSUE THREAD

**Issue by d4nyll** [Ethaan/leadboard-roles#1]
When I log in (even as `admin@example.com` or `superadmin@example.com`) and try adding 5 points, it does so client-side, since I see the score increase by 5. But then moments later it would go back to the original, because server-side doesn't update and I get the error `update failed: Access denied`

**Comment by Ethaan** [comment]
Fixed =D.

Totally forgot to remove the the statics _ids on the allows methods.
